--- 
services: 
  backend: 
    image: "dto80/234-lab11:latest"
    ports: 
      - "8084:8080"
    volumes:
      - type: bind
        source: ./data
        target: /data
  frontend: 
    image: "meandthefirefly/se234-lab11-frontend:latest"
    ports: 
      - "8085:80"
version: "3.3"
